#
######FUNFANO
#- name: verificando se o arquivo index.html existe
#  command: test -f /var/www/html/index.html
#  register: index
#  ignore_errors: yes
#
#
#- name: mudando o arquivo
#  when: index.rc == 0
#  shell: "echo Ola Mundo > /var/www/html/index.html"
#  ignore_errors: yes
#
#
#
- name: enviando uma index.html para os servidores
  template:
   src: ../files/index.html
   dest: /var/www/html/index.html
  when: ansible_os_family == "Debian"
