---

- name: Realizando o Download do puppet repo Ubuntu xenial
  get_url:
    url: https://apt.puppetlabs.com/puppet5-release-xenial.deb
    dest: /tmp/puppet.deb
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "xenial"

- name: Adicionando o pacote do puppet no repositorio do Ubuntu
  apt:
    deb: /tmp/puppet.deb
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "xenial"

- name: Adicionando o pacote do puppet no repositorio do CentOS
  when: ansible_distribution_major_version == "7"
  yum:
   name: https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm


#- name: Download puppet repo CentOS
#  get_url:
#   url: https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
#   dest: /tmp/puppet.rpm
#  when: ansible_os_family == "RedHat"
#
#- name: Instalando o pacote do puppet no CentOS
#  yum:
#   name: /tmp/puppet.rpm
#  when: ansible_hostname == "RedHat"

