---
# tasks file for web

######FUNFANDO
#- name: instalando apache
#  package:
#   name: apache2
#  when: ansible_os_family == "Debian"
#
#
#
#
#######FUNFANDO
#- name: chamando a playbook instalando
#  include: instalando.yaml
#
#- name: chamando a playbook do arquivo
#  include: create.yaml
#
- name: chamando playbook debian
  include: deb_instalapkg.yaml

- name: chamando playbook centos
  include: centos_instalapkg.yaml
