---
# tarefas relacionadas ao repositorio

- name: DOCKER Instalando prerequisitos
  apt: name={{item}} update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: DOCKER Adicionando GPG Key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg 
    id: 0EBFCD88
    state: present

- name: DOCKER Adicionando instalador ao repositorio
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "xenial" and ansible_hostname == "docker"
