---
- name: Minha primeira playbook
  hosts: all
  tasks:
    - name: Copiando um arquivo
      copy: 
        src: /etc/ansible/playbooks/devops
        dest: /tmp/devops

- name: Copiar arquivo \"/etc/resolv.conf\"
  hosts: docker automation
  tasks:
    - name: Copiando arquivo resolv.conf
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf

- name: Instalando o pacote sl em maquinas Debian
  hosts: devops docker
  tasks:
    - name: Instalando o pacote sl
      apt:
        name: sl
        update_cache: yes
        state: present
...
